stages:
  - lint
  - test
  - e2e
  - coverage
  - security
  - sonar

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -m venv venv
  - source venv/Scripts/activate
  - pip install --upgrade pip
  - pip install pylint bandit pytest pytest-cov

lint:
  stage: lint
  script:
    - pylint main.py --output-format=json:pylint-report.json

test:
  stage: test
  script:
    - pytest --cov=main --cov-report=xml:coverage.xml

e2e:
  stage: e2e
  image: selenium/standalone-chrome:latest 
  script:
    - pytest test/e2e/test_selenium.py

coverage:
  stage: coverage
  script:
    - pytest --cov=main --cov-report=xml:coverage.xml

security:
  stage: security
  script:
    - bandit -r . -f json -o bandit-report.json
    - docker pull aquasec/trivy:latest
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $CI_PROJECT_DIR:/project aquasec/trivy:latest image --format json -o trivy-report.json my-docker-image:latest

sonar:
  stage: sonar
  script:
    - sonar-scanner
